# Generated by Django 5.1.3 on 2024-11-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.TextField(
                        help_text="Введите тему", max_length=100, verbose_name="тема"
                    ),
                ),
                (
                    "letter",
                    models.TextField(
                        help_text="Введите сообщение", verbose_name="сообщение"
                    ),
                ),
            ],
            options={
                "verbose_name": "письмо",
                "verbose_name_plural": "письма",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Введите получателя",
                        max_length=250,
                        verbose_name="Ф.И.О.",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        help_text="Введите Email",
                        max_length=250,
                        unique=True,
                        verbose_name="Email ",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Введите комментарий",
                        max_length=250,
                        verbose_name="комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
        migrations.CreateModel(
            name="NewsLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_sent_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Создана", "Создана"),
                            ("Запущена", "Запущена"),
                            ("Завершена", "Завершена"),
                        ],
                        default="Создана",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_projects.message",
                    ),
                ),
                ("recipients", models.ManyToManyField(to="web_projects.user")),
            ],
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_time", models.DateTimeField(verbose_name="дата создания")),
                (
                    "status",
                    models.CharField(
                        choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                        max_length=20,
                    ),
                ),
                ("server_response", models.TextField(blank=True)),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send_attempts",
                        to="web_projects.newsletter",
                    ),
                ),
            ],
        ),
    ]
