# Generated by Django 5.1.3 on 2024-11-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Введите Email",
                max_length=250,
                unique=True,
                verbose_name="Email ",
            ),
        ),
    ]
