# Generated by Django 5.1.3 on 2024-12-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_projects", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "permissions": [
                    ("can_activ_user", "Can activ user"),
                    ("can_activ_newsletter", "Can activ newsletter"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AddField(
            model_name="newsletter",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
